---
title: "Заметки по R"
author: "Борис Демешев"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
lang: russian
---

#### Знакомство с R
* [R --- веселый калькулятор](cycle_files/08_fancy_calc.html)
* [Преобразования данных](cycle_files/18_data_transform.html)

#### Метод наименьших квадратов
* [Апельсины и простая регрессия](cycle_files/02_ols_oranges.html)
* [Мультиколлинеарность](cycle_files/05_multicollinearity.html)
* [Гетероскедастичность](cycle_files/12_hetero.html)

#### Модели качественных данных


* [Работа с качественными переменными](cycle_files/01_qualitative_variable.html)
* [Логит и пробит модели](cycle_files/03_logit_regression.html)
* [Визуализация результатов logit регрессии](cycle_files/04_qualit_graphs.html)

#### Модели панельных данных
* [Панельные данные](cycle_files/09_panel_regression.html)

#### Алгоритмы 
* [Метод максимального правдоподобия](cycle_files/17_ml.html)
* [Метод опорных векторов](cycle_files/11_svm.html)
* [Случайный лес](cycle_files/22_forest.html)

* [Метод главных компонент](cycle_files/06_pca.html)
* [Квантильная регрессия](cycle_files/07_quant_reg.html)
 




#### Временные ряды
* [ARMA модели](cycle_files/31_arma_models.html)
* Единичный корень сотоварищи
* GARCH
* VAR/VECM: [пересказ от rakhab](http://rpubs.com/rakhab/9941) виньетки vars
* [Байесовские VAR модели](cycle_files/21_bayesian_var.html)

#### Байесовский подход
* [Иерархический мультиномиальный логит](cycle_files/32_bayesian_hierarchical_logit.html)
* [Введение в STAN](cycle_files/33_stan_intro.html)
* Иерархический мультиномиальный логит в JAGS
* [MCMC для стандартных моделей](cycle_files/15_mcmc_pack.html)

#### Специфика R
* [Облачные вычисления с R](cycle_files/19_cloud.html)
* [Создание своего пакета R](cycle_files/20_package.html)
* [R внутри документов](cycle_files/26_literate_programming.html)

#### Источники данных
* [Загрузка данных по России](cycle_files/23_load_rus_data.html)
* Работа с данными rlms (план)





#### Динамическая оптимизация
* [Дифференциальные уравнения](cycle_files/10_diff_eq.html)
* Задачи динамической оптимизации

#### Прочее
* 25. Графики --- дело тонкое!
* 13. Парсинг 
* 14. Карты
* 16. Смешные xkcd-графики Хм! Тут в самую тему непараметрическая регрессия!


Открыв любую заметку и заменив в адресной строке браузера разрешение `html` на `Rmd` можно увидеть исходный текст, по которому создавалась страничка.

Репозиторий [заметок на гитхабе](https://github.com/bdemeshev/r_cycle). Скачать все [заметки в один клик](https://github.com/bdemeshev/r_cycle/archive/gh-pages.zip).

Свободный доступ к научным статьям на [sci-hub](http://www.sci-hub.cc) :)

Заметки распространяются по лицензии [Creative Commons Attribution-NonCommercial-ShareAlike](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.ru)



